#!/bin/sh

# script/setup: Set up the application for the first time after cloning, or set
#               it back to the initial unused state.

set -e

cd "$(dirname "$0")/.."

if [ -d node_modules ]; then
  echo "==> Cleaning installed dependencies..."
  git clean -x --force -- node_modules
fi

echo "==> Bootstrapping..."
script/bootstrap
