#!/bin/sh

# script/test: Run the test suite for the application. Optionally pass in a path
#              to an individual test file to run a single test.

set -e

cd "$(dirname "$0")/.."

if [ -n "$DEBUG" ]; then
  set -x
fi

echo "==> Updating..."
script/update

TEST_FILE=$1

if [ -n "$TEST_FILE" ]; then
  echo "==> Running the tests matching '$TEST_FILE'..."
  npm test -- "$TEST_FILE"
else
  if [ -n "$CI" ]; then
    echo "==> Checking formatting..."
    npm run-script lint:format
  else
    echo "==> Formatting files..."
    npm run-script lint:format:fix
  fi

  echo "==> Running ShellCheck..."
  shellcheck script/*

  if [ -n "$CI" ]; then
    echo "==> Linting JS..."
    npm run-script lint:js
  else
    echo "==> Linting JS in fix mode..."
    npm run-script lint:js:fix
  fi

  echo "==> Running the tests..."
  npm test
fi
