#!/bin/sh

# script/test: Run the test suite for the application. Optionally pass in a path
#              to an individual test file to run a single test.

set -e

cd "$(dirname "$0")/.."

if [ -n "$DEBUG" ]; then
  set -x
fi

echo "==> Updating..."
script/update

TEST_FILE=$1

if [ -n "$TEST_FILE" ]; then
  echo "==> Running the tests matching '$TEST_FILE'..."
  bundle exec rspec --pattern "$TEST_FILE"
else
  echo "==> Running ShellCheck..."
  shellcheck script/*

  if [ -n "$CI" ]; then
    echo "==> Linting Ruby files..."
    bundle exec standardrb
  else
    echo "==> Linting Ruby files in fix mode..."
    bundle exec standardrb --fix
  fi

  echo "==> Running the tests..."
  bundle exec rspec
fi
