#!/bin/sh

# script/setup: Set up the application for the first time after cloning, or set
#               it back to the initial unused state.

set -e

cd "$(dirname "$0")/.."

if [ -f Gemfile ] && [ -d vendor/bundle ]; then
  echo "==> Cleaning installed Ruby dependencies..."
  git clean -x --force -- vendor/bundle
fi

if [ -f package.json ] && [ -d node_modules ]; then
  echo "==> Cleaning installed JS dependencies..."
  git clean -x --force -- node_modules
fi

echo "==> Bootstrapping..."
script/bootstrap
