#!/bin/sh

# script/test: Run the test suite for the application. Optionally pass in a path
#              to an individual test file to run a single test.

set -e

cd "$(dirname "$0")/.."

if [ -n "$DEBUG" ]; then
  set -x
fi

echo "==> Updating..."
script/update

TEST_FILE=$1

if [ -n "$TEST_FILE" ]; then
  echo "==> Running the tests matching '$TEST_FILE'..."
  echo "No testing instructions configured!"
  exit 1
else
  echo "==> Running ShellCheck..."
  shellcheck script/*

  echo "==> Running the tests..."
  echo "No testing instructions configured!"
  exit 1
fi
