#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f .gitmodules ]; then
  echo "==> Updating Git submodules..."
  git submodule update --init
fi

if [ -z "$CI" ]; then
  if [ -f Brewfile ] && [ "$(uname -s)" = "Darwin" ]; then
    if ! brew bundle check >/dev/null 2>&1; then
      echo "==> Installing Homebrew dependencies..."
      brew bundle install --verbose
    fi
  fi

  if [ -f .ruby-version ]; then
    eval "$(rbenv init -)"

    if [ -z "$(rbenv version-name 2>/dev/null)" ]; then
      echo "==> Installing Ruby..."
      rbenv install --skip-existing
      rbenv rehash
    fi
  fi
fi

if ! command -v bundle >/dev/null 2>&1; then
  echo "==> Installing Bundler..."
  gem install bundler

  if [ -z "$CI" ]; then
    rbenv rehash
  fi
fi

if ! bundle check >/dev/null 2>&1; then
  echo "==> Installing Ruby dependencies..."
  bundle install --path vendor/bundle
fi
