#!/bin/sh

# script/setup: Set up the application for the first time after cloning, or set
#               it back to the initial unused state.

set -e

cd "$(dirname "$0")/.."

if [ -d vendor/bundle ]; then
  echo "==> Cleaning installed Ruby dependencies..."
  git clean -x --force -- vendor/bundle
fi

echo "==> Bootstrapping..."
script/bootstrap
