on:
  - push
  - pull_request

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Update Homebrew
        run: brew update

      - name: Perform setup
        run: script/setup

      - name: Run tests
        run: script/test
