on:
  - push
  - pull_request

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Update Homebrew
        run: brew update

      - name: Perform setup
        run: script/setup

      - name: Run tests
        run: script/test
